-- 016_jobs_data_limited.sql  (ORPHEUS-88)
--
-- Denormalized "this report rests on limited data" flag on the job row.
--
-- The full data-quality report lives in ingested_data.quality_report (JSONB),
-- visible to no one. ORPHEUS-88 adds a client-facing report banner and an
-- advisor/admin chip for reports that completed on incomplete/degraded data.
-- The banner (single-job GET /jobs/{id}) reads the full report and lists the
-- specific notices; the list/roster surfaces (GET /jobs, GET /clients,
-- /admin/jobs, /admin/clients) need only a cheap boolean and shouldn't pay to
-- parse a large JSONB per row — hence this denormalized flag.
--
-- Set by the worker at pipeline completion to quality_report.is_data_limited
-- (any CRITICAL/WARNING in the data-limitation categories: missing_file,
-- empty_data, parse_failure, date_range — MISSING_FIELD and INFO excluded).
-- Blocking missing-file criticals never reach the worker — they're rejected
-- at POST /jobs — so this reflects allowed-through EMPTY_DATA criticals plus
-- data-limitation warnings.
--
-- Defaults to false. Pre-ORPHEUS-88 complete jobs stay false.
--
-- NO BACK-FILL (deliberate). The obvious back-fill — read each stored
-- ingested_data.quality_report and set the flag where a data-limitation
-- issue is present — is NOT reliable: those historical reports were
-- generated by the pre-ORPHEUS-87 parser, which was blind to
-- member-ID-suffixed CSVs (Shares_<id>.csv, Comments_<id>.csv, ...) and so
-- wrongly emitted missing_file criticals/warnings for archives that were
-- actually complete. A one-session probe found 28 jobs with a
-- critical/missing_file flag and 31 with warning/missing_file — mostly that
-- suffix false-positive, not genuine limited data. Back-filling from them
-- would chip ~33 historical reports as "limited data" when most were fine.
-- So the flag populates only for jobs scored after this ships (post-87
-- parser + the worker write in run_pipeline). Same posture as ORPHEUS-97
-- for config_snapshot model provenance: historical rows can't be trusted,
-- so they stay at the default rather than get a heuristic back-fill.
--
-- The worker picks up nothing new here (it writes the column directly);
-- claim_next_job (migration 006) returns SELECT * so the column also flows
-- into the claimed job dict harmlessly.

ALTER TABLE public.jobs
    ADD COLUMN IF NOT EXISTS data_limited boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN public.jobs.data_limited IS
    'ORPHEUS-88: true when the completed report rests on incomplete/degraded LinkedIn data (allowed-through EMPTY_DATA critical or data-limitation warnings). Denormalized from ingested_data.quality_report at completion for cheap list/roster chips. Missing-file criticals are rejected at POST /jobs and never set this. No back-fill — pre-87 stored quality_reports over-report missing files.';
